# Generated by Django 5.0.6 on 2026-03-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationschedule',
            name='custom_time',
            field=models.TimeField(blank=True, help_text="Required when time_of_day is 'custom'.", null=True),
        ),
    ]
