# Generated by Django 5.0.6 on 2026-03-15 09:59

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seniors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('medical_report', 'Medical Report'), ('prescription', 'Prescription'), ('lab_result', 'Lab Result'), ('insurance', 'Insurance'), ('identity', 'Identity Document'), ('consent_form', 'Consent Form'), ('referral', 'Referral'), ('discharge_summary', 'Discharge Summary'), ('other', 'Other')], default='other', max_length=30)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Free-form tags for additional filtering', size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('senior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='seniors.senior')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_number', models.PositiveSmallIntegerField()),
                ('mime_type', models.CharField(max_length=30)),
                ('file_size', models.PositiveIntegerField(help_text='Size in bytes')),
                ('content', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='documents.document')),
            ],
            options={
                'verbose_name': 'document page',
                'verbose_name_plural': 'document pages',
                'ordering': ['document', 'page_number'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='document_tags_gin'),
        ),
        migrations.AlterUniqueTogether(
            name='documentpage',
            unique_together={('document', 'page_number')},
        ),
    ]
